const USER_ROLES = {
  CUSTOMER: "customer",
  ADMIN: "admin",
};

const USER_STATUS = {
  ACTIVE: true,
  INACTIVE: false,
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
};

const JWT_CONFIG = {
  DEFAULT_EXPIRES_IN: "7d",
  ALGORITHM: "HS256",
};

const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
};

const ERROR_TYPES = {
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_TOKEN: "BAD_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
};

module.exports = {
  USER_ROLES,
  USER_STATUS,
  HTTP_STATUS,
  JWT_CONFIG,
  PAGINATION,
  ERROR_TYPES,
};
