const USER_ROLES = {
  CUSTOMER: "customer",
  ADMIN: "admin",
};

const USER_STATUS = {
  ACTIVE: true,
  INACTIVE: false,
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
};

const JWT_CONFIG = {
  DEFAULT_EXPIRES_IN: "7d",
  ALGORITHM: "HS256",
};

const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
};

const ERROR_TYPES = {
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_TOKEN: "BAD_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
};

const UPLOAD_LIMITS = {
  FILE_SIZE: {
    IMAGE: 5 * 1024 * 1024,      // 5MB
    VIDEO: 50 * 1024 * 1024,     // 50MB
    AVATAR: 2 * 1024 * 1024,     // 2MB
  },
  MAX_COUNT: {
    PRODUCT_IMAGES: 10,
    PRODUCT_VIDEOS: 2,
  }
};

const ALLOWED_FORMATS = {
  IMAGES: ['jpg', 'jpeg', 'png', 'gif', 'webp'],
  VIDEOS: ['mp4', 'mov', 'avi', 'mkv'],
};

const COLOR_OPTION_NAMES = ["Màu", "Màu sắc"];
const SIZE_OPTION_NAMES = ["Size", "Kích cỡ"];

module.exports = {
  USER_ROLES,
  USER_STATUS,
  HTTP_STATUS,
  JWT_CONFIG,
  PAGINATION,
  ERROR_TYPES,
  UPLOAD_LIMITS,
  ALLOWED_FORMATS,
  COLOR_OPTION_NAMES,
  SIZE_OPTION_NAMES,
};
