name: Deploy to AWS EC2

on:
  push:
    branches:
      - staging

env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ec2-user
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
  EC2_DOMAIN: ${{ secrets.EC2_DOMAIN }}

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Build frontend
        working-directory: ./frontend
        run: |
          echo "VITE_API_URL=http://${{ secrets.EC2_DOMAIN }}/api" > .env.production
          npm ci
          npm run build

      - name: Upload frontend build
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "frontend/dist"
          target: "/home/ec2-user/mini-ecommerce-app/frontend"

  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/mini-ecommerce-app/backend
            git fetch origin
            git checkout staging
            git pull origin staging
            docker compose down
            docker compose up -d --build

  deploy-frontend:
    needs: [build-frontend, deploy-backend]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/mini-ecommerce-app/frontend
            git fetch origin
            git checkout staging
            git pull origin staging
            docker compose up -d --build
