name: Deploy to AWS EC2

on:
  push:
    branches:
      - staging

env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ec2-user
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
  EC2_DOMAIN: ${{ secrets.EC2_DOMAIN }}

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/mini-ecommerce-app/backend
            git fetch origin
            git checkout staging
            git pull origin staging
            docker-compose down
            docker-compose up -d --build

  deploy-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest

    steps:
      - name: Deploy frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/mini-ecommerce-app/frontend
            git fetch origin
            git checkout staging
            git pull origin staging
            VITE_API_URL=http://${{ secrets.EC2_DOMAIN }}/api docker-compose up -d --build
